name: Code Coverage

on: push

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clojure deps cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: $${ runner.os }}-cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: $${ runner.os }}-cljdeps-

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install babashka
      run: curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install | sudo bash

    - name: Install clojure
      run: curl -s https://download.clojure.org/install/linux-install-1.10.3.967.sh | sudo bash

    - name: Tools versions
      run: |
        echo "bb --version"
        bb --version
        echo "java -version"
        java -version
        echo "clojure -Sdescribe"
        clojure -Sdescribe

    - name: Download clojure dependencies
      run: clojure -Spath

    - name: Run Tests with Code Coverage
      run: bb test-coverage

    - name: Upload Code Coverage Results
      run: |
        echo "Downloading codecov uploader script"
        curl -s https://codecov.io/bash > codecov
        echo "Verifying codedov uploader script"
        VERSION=$(grep 'VERSION=\".*\"' codecov | cut -d'"' -f2);
        for i in 1 256 512
        do
          sha${i}sum -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM")
        done
        echo "Uploading to codecov"
        bash codecov -f target/coverage/codecov.json
