name: Libs Test

on: push

jobs:
  libs-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Clojure deps cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        # base cache on libs_test.clj script for now... lib deps are embedded in it
        key: $${ runner.os }}-clj-libs-deps-${{ hashFiles('script/libs_tests.clj') }}
        restore-keys: $${ runner.os }}-clj-libs-deps-

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Install Babashka
      run: curl -s https://raw.githubusercontent.com/borkdude/babashka/master/install | sudo bash

    - name: Install Clojure
      run: curl -s https://download.clojure.org/install/linux-install-1.10.1.763.sh | sudo bash

    - name: Tools versions
      run: |
        echo "bb --version"
        bb --version
        echo "java -version"
        java -version
        echo "clojure -Sdescribe"
        clojure -Sdescribe
        echo "lein --version"
        lein --version

    - name: Run Libs Tests
      run: bb ./script/libs_tests.clj
