name: Native Image Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        sys:
          # override the default of pwsh for windows
          - { os: windows, shell: powershell }
          - { os: ubuntu,  shell: bash  }
          - { os: macos,   shell: bash  }
        graal-java: [ 11 ]
        test: [ test-native, test-native-sci ]
        clojure-version: [ '1.11' ]

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    name: ${{ matrix.sys.os }},jdk ${{ matrix.graal-java }},${{ matrix.test }},clj ${{ matrix.clojure-version }}

    steps:
    - uses: actions/checkout@v3

    #
    # Caches
    #
    - name: Clojure deps cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: ${{ runner.os }}-cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: ${{ runner.os }}-cljdeps-

    #
    # Install GraalVM
    #
    - name: Install GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.0.0.2'
        java-version: ${{ matrix.graal-java }}
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    #
    # Install Clojure, Babashka
    #
    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@5.0
      with:
        cli: 1.11.1.1105
        bb: 'latest'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    #
    # Summarize installs
    #
    - name: Tools versions
      run: |
        echo "bb --version"
        bb --version
        echo "java -version"
        java -version
        echo "clojure -Sdescribe"
        clojure -Sdescribe

    #
    # Prep Clojure
    #
    - name: Download clojure dependencies
      run: clojure -Spath

    #
    # native image tests
    #
    - name: Execute ${{ matrix.test }} native test
      run: bb ${{ matrix.test }} --clojure-version ${{ matrix.clojure-version }}
