name: Native Image Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        graal-java: [ 11 ]
        test: [ test-native, test-native-sci ]
        clojure-version: [ '1.11' ]

    name: ${{ matrix.os }},jdk ${{ matrix.graal-java }},${{ matrix.test }},clj ${{ matrix.clojure-version }}

    steps:
    - uses: actions/checkout@v3

    #
    # Caches
    #
    - name: Clojure deps cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: $${ runner.os }}-cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: $${ runner.os }}-cljdeps-

    #
    # Install GraalVM
    #
    - name: Install GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: '22.0.0.2'
        java-version: ${{ matrix.graal-java }}
        components: 'native-image'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    #
    # Install Babashka
    #
    - name: Install babashka
      uses: turtlequeue/setup-babashka@v1.3.0
      with:
        babashka-version: 0.7.8

    #
    # Install Clojure
    #
    - name: Install clojure (windows)
      # On windows, deps.clj's deps.exe is used in place of clojure to avoid complexities of official clojure install
      run: |
       PowerShell -Command "iwr -useb https://raw.githubusercontent.com/borkdude/deps.clj/master/install.ps1 | iex"
       Rename-Item $HOME\deps.clj\deps.exe clojure.exe
       echo "$HOME\deps.clj" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      if: matrix.os == 'windows-latest'
    - name: Install clojure (macos)
      run: brew install clojure/tools/clojure
      if: matrix.os == 'macos-latest'
    - name: Install clojure (linux)
      run: curl -s https://download.clojure.org/install/linux-install-1.10.3.986.sh | sudo bash
      if: matrix.os == 'ubuntu-latest'

    - name: Bring down ClojureTools early
      run: clojure -Sdescribe

    #
    # Summarize installs
    #
    - name: Tools versions
      run: |
        echo "bb --version"
        bb --version
        echo "java -version"
        java -version
        echo "clojure -Sdescribe"
        clojure -Sdescribe

    #
    # Prep Clojure
    #
    - name: Download clojure dependencies
      run: clojure -Spath

    #
    # native image tests
    #
    - name: Execute ${{ matrix.test }} native test
      run: bb ${{ matrix.test }} --clojure-version ${{ matrix.clojure-version }}
