name: Unit Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.sys.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        sys:
          # override the default of pwsh for windows
          - { os: windows, shell: powershell }
          - { os: ubuntu,  shell: bash  }
          - { os: macos,   shell: bash  }
        java: [ '8', '11', '17' ]

    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    name: ${{ matrix.sys.os }},jdk ${{ matrix.java }}

    steps:
    #
    # Tell git not to convert newlines on checkout for Windows
    #
    - name: Prepare git (Windows)
      run: git config --global core.autocrlf false
      if: matrix.sys.os == 'windows'

    - uses: actions/checkout@v3

    #
    # Caches
    #
    - name: Clojure deps cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: ${{ runner.os }}-cljdeps-${{ hashFiles('deps.edn') }}
        restore-keys: ${{ runner.os }}-cljdeps-

    - name: Node modules cache
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: $${ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: $${ runner.os }}-node-

    #
    # Setup Java
    #
    - name: "Setup Java"
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    #
    # Install Planck
    #
    - name: Install planck (macOS)
      run: brew install planck
      if: matrix.sys.os == 'macos'
    - name: Install planck (linux)
      run: |
        sudo add-apt-repository -y ppa:mfikes/planck
        sudo apt-get update
        sudo apt-get install -y planck
      if: matrix.sys.os == 'ubuntu'
    - name: Install planck (macOS)
      run: brew install planck
      if: matrix.sys.os == 'macos'

    #
    # Install Clojure & Babashka
    #
    - name: Install Clojure tools
      uses: DeLaGuardo/setup-clojure@5.0
      with:
        cli: 1.11.1.1105
        bb: 'latest'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    #
    # Summarize installs
    #
    - name: Tools versions
      run: |
        echo "bb --version"
        bb --version
        echo "node --version"
        node --version
        echo "java -version"
        java -version
        echo "clojure -Sdescribe"
        clojure -Sdescribe
    - name: Tools versions (macos, linux)
      run: |
        echo "planck --version"
        planck --version
      if: matrix.sys.os != 'windows'

    #
    # Node modules
    #
    - name: Install karma command line (windows)
      run: npm install karma-cli -g
      if: matrix.sys.os == 'windows'
    - name: Install karma command line (macos, linux)
      run: sudo npm install karma-cli -g
      if: matrix.sys.os != 'windows'

    - name: Install node modules
      run: npm install

    #
    # Prep Clojure
    #
    - name: Download clojure main dependencies
      run: clojure -Spath

    #
    # Run tests
    #
    - name: Run CI tests
      run: bb ci-unit-tests
